module.exports = {
  API_URL:     $PROCESS_ENV_API_URL     || 'http://localhost:3000',
  PEERJS_HOST: $PROCESS_ENV_PEERJS_HOST || 'localhost',
  PEERJS_PORT: $PROCESS_ENV_PEERJS_PORT || '9000',
  FACEBOOK_ID: $PROCESS_ENV_FACEBOOK_ID || '1488551384779862'
};
